title: Site

columns:
    left:
        width: 1/3
        sections:
            call-paper:
                label: Appels de textes
                type: pages
                parent: site.find("actualites").find("appels-de-textes")
                template: call-for-papers
            call-talk:
                label: Appels à communications
                type: pages
                parent: site.find("actualites").find("appels-a-communications")
                template: call-for-presentations
            conference:
                label: Colloques
                type: pages
                parent: site.find("actualites").find("colloques")
                template: conference
    right:
        width: 2/3
        sections:
            issues:
                extends: sections/issues
                parent: site.find("parutions")
